### ISSUE TITLE
Markbot Issue - Index.html - Required Elements 

### ISSUE THREAD

**Issue by DDesousa0517** [DDesousa0517/dinosaur-designs#1]
My tutor and I can't figure out why we continue to get the following error in Markbot:

index.html - Required elements
- The Hadrosaur navigation link doesn't point to the Hadrosaur information
- The Iguanodon navigation link doesn't point to the Iguanodon information
- The Stegosaurus navigation link doesn't point to the Stegosaurus information

Sreenshots - index - 320px
-Too visually different from screenshot (23% difference)
_... I am assuming this is because of the error above and will correct itself once I have corrected the above info._ 

@thomasjbradley

Thank you,
Darcie

**Comment by thomasjbradley** [comment]
*Navigation link problems—*

Remove the word `jump-point` in the IDs, leaving just the name of the dinosaur.

This line here:
https://github.com/DDesousa0517/dinosaur-designs/blob/gh-pages/index.html#L16

Should look like this:

```html
<li><a href="#hadrosaur">Hadrosaur</a></li>
```

**And don’t forget to change the matching IDs too.**

---

*Screenshots—*

When you open up Markbot’s screenshot comparison window, if you look further down, looking at the captions for the bottom two dinosaurs, the text-size is too big. Only the first dinosaur should have the enlarged font-size.

**Comment by DDesousa0517** [comment]
Thank you for your help
